# Generated by Django 4.1.5 on 2023-10-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='copass',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
