# Generated by Django 4.1.5 on 2023-10-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
