# Generated by Django 4.1.5 on 2023-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_woregi_login_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='rights',
        ),
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(),
        ),
    ]
