# Generated by Django 4.1.5 on 2023-10-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_login_rights_alter_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job_name', models.CharField(max_length=30)),
                ('DOB', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('licence', models.FileField(upload_to='')),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
