# Generated by Django 4.1.5 on 2023-10-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_entry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.AddField(
            model_name='woregi',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
