# Generated by Django 4.1.5 on 2023-10-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_status_woregi_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woregi',
            name='action',
        ),
        migrations.AddField(
            model_name='entry',
            name='action',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
