# Generated by Django 4.1.5 on 2023-10-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_woregi_action_entry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='select',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
