# Generated by Django 4.1.5 on 2023-12-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_chosse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='gender',
        ),
        migrations.AddField(
            model_name='entry',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
