# Generated by Django 4.1.5 on 2024-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ufeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=30)),
                ('feed', models.CharField(max_length=30)),
            ],
        ),
    ]
